--------------------------------
-- PART TO WHOLE Analysis (Proportional Analysis)
--------------------------------

/*

Comparing individual part to the overall.
It can allow us to understand which category has greater or lower impact on the business.

Ex: 

(sales/total_sales)*100 by country - to find highest selling product or highest revenue generated by country

Which categories contribute to the most to overall sales?

*/


-- Which categories contribute to the most to overall sales?

WITH CTE AS (
SELECT 
p.category,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
)

SELECT
*,
SUM(total_sales) OVER() overall_sales,
CAST (total_sales AS FLOAT)/SUM(total_sales) OVER()*100 AS category_percent 
FROM CTE;


-- Always need to terminate the CTE expressions with ';' before jumping to other query

/*
In the above query we casted total_sales to Float to get valid decimal numbers for our percentage. 

In below query we will:

1. Take the entire line of category_percent inside a Round function to get only 2 decimal numbers
2. Then take the category_percent inside a CONCAT function to show % format
3. ORDER BY total_sales to see highest value on top
----------------------------

Query might get clumpsy to understand, so breaking it down for anyone who wants to understand.

*/


WITH category_sales AS (
SELECT 
p.category,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
)

SELECT
*,
SUM(total_sales) OVER() overall_sales,
CONCAT(ROUND((CAST (total_sales AS FLOAT)/SUM(total_sales) OVER())*100,2),'%') AS category_percent 
FROM category_sales
ORDER BY total_sales DESC